### ISSUE TITLE
New Nemo converter cant convert to jxl or avif. 

### ISSUE THREAD

**Issue by Username23453** [Lich-Corals/linux-file-converter-addon#34]

**Comment by Lich-Corals** [comment]
Please provide more information about your issue, I can't reproduce your issue.
Please also start the script manually in the terminal by running these commands:
```bash
cd ~/.local/share/nemo/actions/

python nautilus-fileconverter.py /path/to/example/image/file.png
```
If there are any errors, they may help to identify the issue.

**Comment by Lich-Corals** [comment]
The warning you get seems to be a thing I just didn't think about when I ported the script; it shouldn't be a problem for the script. All that it tells you is, that there is a root installation of the Nautilus version.

I have an idea what it might be, please open the properties of the image you want to convert and tell me what the "Type" value is. There should be something like "image/avif" in it, that's what I need to know.
And, just for my understanding, does it show no options in the dropdown, or just not the ones you need?

**Comment by Lich-Corals** [comment]
Okay, I had a problem with this type before. Probably the only fix is, to uncomment line 140 of the script. It currently looks like this:
```python
#                      'application/octet-stream', <-- Didn't make any problems in nautilus, but Nemo takes all files in it (.zip, .doc, .pdf, etc.) instead of only the image types.
```
And it should look like this:
```python
                      'application/octet-stream',
```
It may be a problem if the formatting is not perfectly inline with the other formats:
```python
# It has to look like this...
                      [...]
                      'image/vnd.net-fpx',
                      'application/octet-stream',
                      'windows/metafile',
                      [...]
# ...and not like this:
                      [...]
                      'image/vnd.net-fpx',
                     'application/octet-stream',
                      'windows/metafile',
                      [...]
```

There is one problem with uncommenting it: It will enable the context menu for a lot of files, which can't be converted, because the mimetype 'application/octet-stream' includes files like .zip, .doc and .pdf.

I will have a look at how to solve it in a better way later, but I think it should work for now to just uncomment it.

**Comment by Lich-Corals** [comment]
It's important that you put a comma at the end of the line; like this:
```bash
'application/octet-stream',
```

**Comment by Lich-Corals** [comment]
I don't think it's a problem with the other scripts, but it won't hurt to try it without those.

I will take a closer look at the problem in the next days, I don't have much time right now.

**Comment by Lich-Corals** [comment]
I thought about it a bit more, I'm not sure, why it doesn't work for your files, but I think it is a problem with the mime type. Could you upload an image, which should work but doesn't, so I can test my solution? I couldn't reproduce this situation so far.

**Comment by Lich-Corals** [comment]
The problem should be fixed now.
I found out, that the script detected a different mimetype for some images, which wasn't in the database. 
I changed the determination method for mimetypes in the Nemo adaption, this should hopefully solve your issue. 

Don't forget to update the script and dependencies before testing the script. (See [this page](https://github.com/Lich-Corals/linux-file-converter-addon/releases/tag/1.2.9) to see what's needed.)

**Comment by Lich-Corals** [comment]
I will write a debug version of the script as soon as possible. Could you give me the endings and mimetypes of the files, which don't work for you? I could convert every but one image you sent me before, the others worked without any problems.

**Comment by Lich-Corals** [comment]
Sorry that it took me so long, I finally finished a debug version for you. I attached the file here; just overwrite the old one and run Nemo using `NEMO_DEBUG=Actions nemo --debug` in your terminal app.
It should spit a lot of debug information about what exactly happens, it should also show any python errors or Nemo errors. Just have a look at the output after trying to convert a few files; you can also send me the output, and I'll look for any error messages or the point where the script stops working.

**Comment by Lich-Corals** [comment]
It is a ModuleNotFoundError, which means that the script wasn't able to find your python-magic installation. I don't have much experience with this issue, but I can provide a few ideas what could help with this.
- You could try reinstalling python-magic using these commands:
```bash
pip uninstall python-magic

pip install python-magic
```

You could also try to install the apt package, as long as this is your package manager:
```bash
sudo apt install libmagic1
```

If you've done this, and it's still not working, you could go to the ["Running the tests" Section of this page](https://github.com/ahupp/python-magic?tab=readme-ov-file#running-the-tests) and see if those tests return any useful information. I haven't tried those, but I'd assume that the official tests should work.
If all of this doesn't solve the problem, I'd recommend opening an issue at [python-magic's GitHub page](https://github.com/ahupp/python-magic), although I don't know how active they are. Another option would be to ask a question on stack overflow, there might be some people who know more about this issue than I do. 

I hope we'll get your issue fixed soon; for now, you can still use the [latest version without the magic library](https://github.com/Lich-Corals/linux-file-converter-addon/archive/refs/tags/1.2.8.zip), which should work better, when not ideal for some file types.

I'm still looking for a better solution than the magic library, but it seems to be a pretty hard problem to determine the mime type without tons of additional libraries, which cause new issues.

**Comment by Lich-Corals** [comment]
> @Lich-Corals , its only one .py file? why did you zip it? haha :)

GitHub doesn't want me to upload a python file in a command, so I have to compress it before uploading it. :D

**Comment by Lich-Corals** [comment]
I'm glad it was so easy to fix.

To run the script manually, you can just run it with the file paths as arguments:
```bash
python path/to/script.py /path/to/file.any
```
I'm not sure if this will return much useful information, because I'd expect it to be a mimetype issue. You could first try to uncomment the 'application/octet-stream' line again, as we did before. Don't forget to leave the comma behind it, otherwise it would return an error.

The problem with the infinite drop-down is there, because there are too many formats it. It's a GTK Problem. You could disable wallpaper and square formats in the config to only get the normal formats; this should fix the issue for now.
I'm working on a better solution, for example two additional drop-downs for the special formats.

**Comment by Lich-Corals** [comment]
I'm glad we finally solved it.
I will probably add a new option to the script in near future, which will allow to add octet-stream to the read formats. 
Please note that your script change will be reset with every update until I add it as a setting; if I do so, I'll write it into the patch notes, then you just have to enable the setting and it will persist with updates.

If your issue is solved, please close the issue; in not, feel free to to continue the conversation.

**Comment by Lich-Corals** [comment]
Thanks for the suggestion, I will add this to my fix list and add it as a new option in the next patch. This should be a really quick change.

**Comment by Lich-Corals** [comment]
Are you sure you enabled the `convertFromOctetStream` setting like described [here](https://github.com/Lich-Corals/linux-file-converter-addon/blob/main/markdown/configuration.md#adaption-specific-options-nemo)?

**Comment by Lich-Corals** [comment]
I'm glad it was easy to fix this time.
I actually know this tool you linked; the creator of it asked for information about my script a few weeks ago, but thanks for mentioning it anyway. :D
